### ISSUE TITLE
Support for other curves?

### ISSUE THREAD

**Issue by nasko25** [DanTehrani/zk-ecdsa-verify#10]
Hello,

I see that your implementation works for ecdsa with secp256k1. Do you plan on adding implementations for other ecdsa curves as well, or is secp256k1 the only curve you plan on using?

Thanks in advance.

**Comment by DanTehrani** [comment]
Hi!

Sorry for the delayed response.
The method can be applied to other signature schemes/curves, but we’re not planning to do implementation on other schemes for now.

**Comment by nasko25** [comment]
I see. Thank you.
